### ISSUE TITLE
linux/arm64 images

### ISSUE THREAD

**Issue by VassilIordanov** [zebernst/synology-csi-talos#16]
Hello,

Many thanks for providing a talos flavor of synology-csi! 

It would be great to also publish images for linux/arm64, do you have plans for that? 

Cheers,
V

**Comment by zebernst** [comment]
This digest should include an arm64 build for the latest commit on main: `ghcr.io/zebernst/synology-csi@sha256:215bd2ee747d1c84407295ab4676a04644e4a4c34ce8bbebded0a50486df5c28`

**Comment by schwankner** [comment]
> This digest should include an arm64 build for the latest commit ([f8a843a](https://github.com/zebernst/synology-csi-talos/commit/f8a843a567bea289e881abbd73ee075ed537b1cd)) on main: `ghcr.io/zebernst/synology-csi@sha256:215bd2ee747d1c84407295ab4676a04644e4a4c34ce8bbebded0a50486df5c28`

Do you mean to make the change in the values.yaml like this?
```yaml
images:
  plugin:
    pullPolicy: Always
    image:
      repository: "ghcr.io/zebernst/synology-csi"
      digest: "sha256:215bd2ee747d1c84407295ab4676a04644e4a4c34ce8bbebded0a50486df5c28"
```
For me this results in this error in the synology-csi-node:
```
  Warning  InspectFailed  7s (x3 over 8s)  kubelet            Failed to apply default image tag "map[digest:sha256:215bd2ee747d1c84407295ab4676a04644e4a4c34ce8bbebded0a50486df5c28 repository:ghcr.io/zebernst/synology-csi]:v1.2.0": couldn't parse image name "map[digest:sha256:215bd2ee747d1c84407295ab4676a04644e4a4c34ce8bbebded0a50486df5c28 repository:ghcr.io/zebernst/synology-csi]:v1.2.0": invalid reference format
  Warning  Failed         7s (x3 over 8s)  kubelet            Error: InvalidImageName

```

and in the synology-csi-controller:

```
  Warning  Failed         2m40s (x12 over 4m40s)  kubelet            Error: InvalidImageName
  Warning  InspectFailed  2m27s (x13 over 4m40s)  kubelet            Failed to apply default image tag "map[digest:sha256:215bd2ee747d1c84407295ab4676a04644e4a4c34ce8bbebded0a50486df5c28 repository:ghcr.io/zebernst/synology-csi]:v1.2.0": couldn't parse image name "map[digest:sha256:215bd2ee747d1c84407295ab4676a04644e4a4c34ce8bbebded0a50486df5c28 repository:ghcr.io/zebernst/synology-csi]:v1.2.0": invalid reference format
```
I use release 0.9.5-pre.1

**Comment by zebernst** [comment]
@schwankner I didn't update the values.yaml file because the tag defaults to `{{ .Chart.AppVersion }}`. Once upstream releases a new version, I will pull the changes in and the default tag will include a multi-platform digest. Until then, folks who need arm64 support can manually specify the digest (as you're doing here).

Your specific issue is because you're using the key `digest` instead of `tag` in your values.yaml. (see how the actual controller value is formatted [here](https://github.com/zebernst/synology-csi-talos/blob/main/charts/synology-csi/templates/controller.yaml#L163)).

Try this instead:
```yaml
images:
  plugin:
    pullPolicy: Always
    image:
      repository: ghcr.io/zebernst/synology-csi
      tag: edge@sha256:215bd2ee747d1c84407295ab4676a04644e4a4c34ce8bbebded0a50486df5c28
```

Let me know if you have any further issues!
